remark: eptn_fraudgt
out_dir: results
device: auto

dataset:
  format: eptn
  name: eptn.pkl
  dir: data
  is_hetero: False
  task: node
  shuffle: True
  task_type: classification
  transductive: True
  split: [0.8, 0.1, 0.1]
  augment_feature: []
  augment_feature_dims: [0]
  augment_feature_repr: position
  augment_label: ''
  augment_label_dims: 0
  transform: none
  node_encoder: False
  edge_encoder: False
  edge_dim: 2

train:
  batch_size: 1
  eval_period: 5
  ckpt_period: 10
  mode: standard
  auto_resume: False
  early_stopping: True
  patience: 10

model:
  type: GTModel
  loss_fun: cross_entropy
  graph_pooling: add

gnn:
  dropout: 0.0

gt:
  head: default
  dim_hidden: 16
  layers: 1
  layers_pre_gt: 0
  layer_type: SparseNodeTransformer
  batch_norm: True
  layer_norm: False
  l2_norm: False
  act: prelu
  input_dropout: 0.0
  dropout: 0.2
  attn_dropout: 0.1
  attn_heads: 1
  attn_mask: Edge
  hops: 1
  edge_weight: False
  residual: Fixed
  ffn: Single
  virtual_nodes: 0
  jumping_knowledge: False

optim:
  optimizer: adam
  base_lr: 0.001
  max_epoch: 100